version: '3.7'

services:
  mongo:
    image: mongo:6.0.5
    container_name: mongo-bnb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: bnb